#pragma once
// Auto-generated by scripts/version_bump.py — do not edit by hand.
// Regenerated on every PlatformIO build.

#define FW_VERSION_MAJOR  1
#define FW_VERSION_MINOR  4
#define FW_VERSION_BUILD  153
#define FW_VERSION_STRING "1.4.153"
#define FW_BUILD_DATE     "2026-09-18 00:08:56"

// Backwards-compatibility aliases for existing consumers in main.cpp.
#define FIRMWARE_VERSION  FW_VERSION_STRING
#define BUILD_NUMBER      FW_VERSION_BUILD
#define BUILD_GIT         "72a5889"
